name: shap-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - tensorflow-gpu
  - cudatoolkit=9.0
  - pytorch
  - torchvision
  - shap
  - numpy
  - scikit-image
  - keras-gpu
  - ipykernel
  - pip:
    - simdna
    - deeplift
    - xgboost
